packages:
  - "."

allowBuilds:
  esbuild: true
  sharp: true

overrides:
  rollup: 4.60.0
  flatted: 3.4.2
  vite: 7.3.5
  sharp: 0.35.0
  yaml: 2.8.3
  picomatch@2: 2.3.2
  picomatch@4: 4.0.5
  postcss: 8.5.24
